#!/usr/bin/env bash
# ------------------------------------------------------------
# Script     : create-django-project
# Descrição  : Script para auxiliar na criação de um projeto django.
# Versão     : 1.0
# Autor      : Marconi S. de Jesus <marconi.developer@outlook.com.br>
# Licença    : GNU/GPL v3.0
# Data       : 06/02/2023
# ------------------------------------------------------------
# Uso: create-django-project 
# ------------------------------------------------------------
clear 

source ~/bin/django-scripts/modules/set_django_enviroment.mod.sh #set_module
source ~/bin/django-scripts/modules/create.mod.sh                #create
source ~/bin/django-scripts/modules/settings.mod.sh              #settings


set_and_active_django_enviroment #set_module
create_project                   #create
create_app                       #create
set_settings                     #settings
